### ISSUE TITLE
Change name from Kyber to MLKEM

### ISSUE THREAD

**Issue by kriskwiatkowski** [post-quantum-cryptography/draft-kwiatkowski-tls-ecdhe-mlkem#11]

**Comment by csosto-pk** [comment]
@kriskwiatkowski , I don't think we should any changes to [draft-kwiatkowski-tls-ecdhe-kyber](https://github.com/post-quantum-cryptography/draft-kwiatkowski-tls-ecdhe-kyber). This draft was to only get a temporary identifier to negotiate in TLS 1.3. This draft serves as the necessary "stable reference" to get the identifier through the "Expert Review process". It should not be considered as a draft that will keep getting updated and ratified.. 

secp384mlkem768 from [draft-ietf-tls-hybrid-design](https://datatracker.ietf.org/doc/draft-ietf-tls-hybrid-design/) was agreed in the TLS WG to be the standards draft which will give us the identifiers for the final ML-KEM spec like `secp392-mlkem768` or `secp392-mlkem1024` or `x25519-mlkem768`.

**Comment by kriskwiatkowski** [comment]
The temporary codepoint is assigned to version -01 of this draft. That's done now.

If we are going to get a codepoint for final version of MLKEM thru draft-ietf-tls-hybrid-design, than that's fine. Otherwise I'll try to use this draft to get it.

**Comment by csosto-pk** [comment]
draft-kwiatkowski-tls-ecdhe-kyber currently only has SecP256r1Kyber768Draft00.

Since that one will make it to [draft-ietf-tls-hybrid-design-09.html#name-defined-hybrid-groups](https://www.ietf.org/archive/id/draft-ietf-tls-hybrid-design-09.html#name-defined-hybrid-groups), what new OIDs were you thinking to include draft-kwiatkowski-tls-ecdhe-kyber?

**Comment by csosto-pk** [comment]
I don't think we do. The codepoint we got already in https://www.iana.org/assignments/tls-parameters/tls-parameters.xhtml#tls-parameters-8 which points to https://datatracker.ietf.org/doc/draft-kwiatkowski-tls-ecdhe-kyber/01/ for SecP256r1Kyber768Draft00 is based on Kyber768 Round 3 (draft-cfrg-schwabe-kyber-02). It is assigned and early adopters deployed it.

Now draft-ietf-tls-hybrid-design will get two "permanent codepoints" for x25519+MLKEM768 and P256+MLKEM768. So, we will have the "final codepoints" from that. Why would we update draft-kwiatkowski-tls-ecdhe-kyber to get codepoints for P256+MLKEM768 since draft-ietf-tls-hybrid-design will do it anyway?
 
Am I misunderstanding you?

**Comment by csosto-pk** [comment]
I was under the impression that from the beginning [draft-ietf-tls-hybrid-design](https://www.ietf.org/archive/id/draft-ietf-tls-hybrid-design-09.html#name-defined-hybrid-groups) was going to get the final `x25519+MLKEM768` and `P256+MLKEM768` OIDs for TLS. I am pretty sure that was the consensus on the list too, but maybe I am misremembering. 

If that is not the case, then indeed another draft needs to get them. 

Are you sure it was said in the meeting that draft-ietf-tls-hybrid-design will not get the final OIDs? I think I will try to go back to the recording too.
